### ISSUE TITLE
"bun install" fails

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale#1]
```
bun install v1.1.38 (bf2f153f)
  ⚙️  esbuild [4/4] Error
    at new ErrorWithFilename (/tmp/prod/node_modules/sumchecker/index.js:29:5)
    at new ChecksumMismatchError (/tmp/prod/node_modules/sumchecker/index.js:36:5)
    at <anonymous> (/tmp/prod/node_modules/sumchecker/index.js:133:24)
    at emit (node:events:70:22)
    at emitReadable_ (node:stream:1665:20)
    at onEofChunk (node:stream:1762:75)
    at readableAddChunk (node:stream:1709:39)
    at <anonymous> (node:stream:3071:24)
    at _flush (node:crypto:1145:43)
    at final (node:stream:3061:20)

```

But then `bun run build` seems to work. Any idea how to fix the error above?

**Comment by Silex** [comment]
Also, `bun run quasar build` or `bun run build` builds everything but then waits infinitly at the end of the process, I need to press CTRL-C. Any idea why this happens?

I'm not far from having docker images for both quasascale backend & frontend.

**Comment by Silex** [comment]
Will open other issues later.
